language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t shumyk/docker-simple-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shumyk/docker-simple-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-simple-react" 
  env: "DockerSimpleReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-857583981603"
  bucket_path: "docker-simple-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
